### ISSUE TITLE
Training my own dataset

### ISSUE THREAD

**Issue by MengqingCao** [autonomousvision/occupancy_networks#101]
My dataset contains 3D .obj data, and I have convertted obj files into off files. However, when I run the sample_mesh.py, it reports error. I wonder how can I solve this problem. Is there anything wrong with the conversion of obj to off files?
Thanks for your reply!

Traceback (most recent call last):
  File "sample_mesh.py", line 226, in <module>
    main(args)
  File "sample_mesh.py", line 76, in main
    process_path(p, args)
  File "sample_mesh.py", line 84, in process_path
    mesh = trimesh.load(in_path, process=False)
  File "/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py", line 135, in load
    **kwargs)
  File "/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/constants.py", line 128, in timed
    result = method(*args, **kwargs)
  File "/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py", line 205, in load_mesh
    **kwargs)
  File "/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/misc.py", line 42, in load_off
    raise NameError('Incorrect number of vertices or faces!')
NameError: Incorrect number of vertices or faces!

**Comment by Uuiiii** [comment]
how do you convert obj files to off files ?this has troubled me for a long time

**Comment by Hxinyue** [comment]
> 我的数据集包含 3D .obj 数据，并且我已将 obj 文件转换为关闭文件。但是，当我运行sample_mesh.py时，它会报告错误。我想知道如何解决这个问题。将 obj 转换为关闭文件有什么问题吗？感谢您的回复！
> 
> 回溯（最近一次调用最后）：文件 “sample_mesh.py”，第 226 行，在 main（args） 文件 “sample_mesh.py”，第 76 行，在 main process_path（p， args） 文件 “sample_mesh.py”，第 84 行，在 process_path mesh = trimesh.load（in_path， process=False） 文件 “/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py”，第 135 行，加载 **kwargs） 文件 “/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/constants.py”，第 128 行，在定时结果中 = method（*args， **kwargs） 文件 “/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py”，第 205 行，load_mesh **kwargs） 文件 “/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/misc.py”，第 42 行，load_off引发 NameError（'不正确的数量顶点或面！名称错误：顶点或面数不正确！

请问您是怎么处理自己的数据集的

**Comment by Pacemak7r** [comment]
> > 我的数据集包含 3D .obj 数据，并且我已经将 obj 文件转为关闭文件。但是，当我运行 sample_mesh.py 时，它会报告错误。我想知道如如何解决这个问题。将obj 转换为关闭文件有什么问题吗？谢谢您的回复！
> > 回源（最近一次调用最后）：文件“sample_mesh.py”，第226行，在main（args）文件“sample_mesh.py”，第76行，在main process_path（p，args）文件“sample_mesh.py”，第84行，在process_path mesh = trimesh.load（in_path，process=False）文件“/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py”，第135行，加载**kwargs）文件“/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/constants.py”，第128行，在确定时结果中=方法（*args，* *kwargs）文件“/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py”，第205行，load_mesh **kwargs）文件“/root/miniconda3/envs /mesh3d/lib/python3.6/site-packages/trimesh/exchange/misc.py”，第 42 行，load_off 引发 NameError（'不正确的数据顶部或面！名称错误：顶部或面数不正确！
> 
> 请问您是怎么​​处理自己的数据集的

你好，请问你会处理自己的数据集了吗

**Comment by Uuiiii** [comment]
啊我处理好了，时间太久远了都忘了



发自我的iPhone


------------------ Original ------------------
From: Zz16ang ***@***.***&gt;
Date: Wed,May 10,2023 3:10 PM
To: autonomousvision/occupancy_networks ***@***.***&gt;
Cc: Uuiiii ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [autonomousvision/occupancy_networks] Training my own dataset(#101)





   
我的数据集包含 3D .obj 数据，并且我已经将 obj 文件转为关闭文件。但是，当我运行 sample_mesh.py 时，它会报告错误。我想知道如如何解决这个问题。将obj 转换为关闭文件有什么问题吗？谢谢您的回复！
 回源（最近一次调用最后）：文件“sample_mesh.py”，第226行，在main（args）文件“sample_mesh.py”，第76行，在main process_path（p，args）文件“sample_mesh.py”，第84行，在process_path mesh = trimesh.load（in_path，process=False）文件“/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py”，第135行，加载**kwargs）文件“/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/constants.py”，第128行，在确定时结果中=方法（args， *kwargs）文件“/root/miniconda3/envs/mesh3d/lib/python3.6/site-packages/trimesh/exchange/load.py”，第205行，load_mesh **kwargs）文件“/root/miniconda3/envs /mesh3d/lib/python3.6/site-packages/trimesh/exchange/misc.py”，第 42 行，load_off 引发 NameError（'不正确的数据顶部或面！名称错误：顶部或面数不正确！
  
请问您是怎么​​处理自己的数据集的
  
你好，请问你会处理自己的数据集了吗
