### ISSUE TITLE
Error occured when loading field inputs of model 

### ISSUE THREAD

**Issue by gokceay** [autonomousvision/occupancy_networks#120]
Hi,

I want to run on my custom dataset and I prepared my data  according to the preprocessed ShapeNet data. I got following error for single image reconstruction with onet : 

Error occured when loading field inputs of model mymodelname

I cannot understand where my error is. Would you please help me regarding this issue?
Thanks in advance

Error occured when loading field inputs of model 101520
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    for batch in train_loader:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
Error occured when loading field inputs of model 101630
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1374, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1400, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/workspace/im2mesh/data/core.py", line 168, in collate_remove_none
    return data.dataloader.default_collate(batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 133, in default_collate
    elem = batch[0]
IndexError: list index out of range

Error occured when loading field inputs of model 100072

**Comment by GloriaSze** [comment]
same issue, have you fixed it?

**Comment by TaroPlay** [comment]
halo,my friend. you said"I want to run on my custom dataset and I prepared my data according to the preprocessed ShapeNet data. ",and I have difficulty in creating my custom dataset.It would be really great if you could help me out.I am looking forword to your reply!

**Comment by yuanjiechen** [comment]
I solved by update numpy to 1.19.5, it caused by im2mesh/data/core.py 116 try except in my case when load image.
