### ISSUE TITLE
undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by spha-code** [autonomousvision/occupancy_networks#25]
I constantly get this error below when I run **python generate.py configs/demo.yaml** on Ubuntu 18.04 anaconda3 cuda 9.0

Can anyone please help? Thanks!

(mesh_funcspace) user@user-FB-22866-One-Computer-Core-i5-46:~/occupancy_networks-master$ python generate.py configs/demo.yaml
Traceback (most recent call last):
  File "generate.py", line 10, in <module>
    from im2mesh import config
  File "/home/user/occupancy_networks-master/im2mesh/config.py", line 4, in <module>
    from im2mesh import onet, r2n2, psgn, pix2mesh, dmc
  File "/home/user/occupancy_networks-master/im2mesh/dmc/__init__.py", line 1, in <module>
    from im2mesh.dmc import (
  File "/home/user/occupancy_networks-master/im2mesh/dmc/config.py", line 2, in <module>
    from im2mesh.dmc import models, training, generation
  File "/home/user/occupancy_networks-master/im2mesh/dmc/models/__init__.py", line 2, in <module>
    from im2mesh.dmc.models import encoder, decoder
  File "/home/user/occupancy_networks-master/im2mesh/dmc/models/encoder.py", line 4, in <module>
    from im2mesh.dmc.ops.grid_pooling import GridPooling
  File "/home/user/occupancy_networks-master/im2mesh/dmc/ops/grid_pooling.py", line 6, in <module>
    from ._cuda_ext import grid_pooling_forward, grid_pooling_backward
ImportError: /home/user/occupancy_networks-master/im2mesh/dmc/ops/_cuda_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by fujingling** [comment]
do you resolved the problem?@spha-code

**Comment by collinskatie** [comment]
@spha-code, @fujingling , or others - did you ever solve this issue? I am also having this error.

**Comment by jvzihaha** [comment]
I had a similar error:/occupancy_networks/im2mesh/dmc/ops/_cuda_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
I solved it by reinstalling a matched version of torch and torch vision.

**Comment by Wakeelfahmed** [comment]
On @jvzihaha suggestion, i resolved by
pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

on python 3.6.15 (running this project on py 3.6 is recommended)

**Comment by fujingling** [comment]
您好，邮件我已收到！
