### ISSUE TITLE
ModuleNotFoundError: No module named 'librender.pyrender'

### ISSUE THREAD

**Issue by itszash** [autonomousvision/occupancy_networks#36]
when i try to run 
**bash dataset_shapenet/build.sh**
i get this error
Processing class 03001627
Converting meshes to OFF
dataset_shapenet/build.sh: line 21: parallel: command not found
Scaling meshes
Create depths maps
Traceback (most recent call last):
  File "../external/mesh-fusion/2_fusion.py", line 11, in <module>
    import librender
  File "/home/zash/Desktop/occupancy_networks-master/external/mesh-fusion/librender/__init__.py", line 6, in <module>
    from librender.pyrender import *
ModuleNotFoundError: No module named 'librender.pyrender'
Produce watertight meshes
Traceback (most recent call last):
  File "../external/mesh-fusion/2_fusion.py", line 11, in <module>
    import librender
  File "/home/zash/Desktop/occupancy_networks-master/external/mesh-fusion/librender/__init__.py", line 6, in <module>
    from librender.pyrender import *
ModuleNotFoundError: No module named 'librender.pyrender'

**Comment by itszash** [comment]
@LMescheder

**Comment by LMescheder** [comment]
Hi @itszash,
did you follow the instructions and have built meshfusion first? Did it build successfully?
Also it seems that you don't have gnu-parallel installed:
```
sudo apt-get install parallel
```

**Comment by itszash** [comment]
yes @LMescheder i build the meshfusion and test it using the usage example and its working fine. but i was sure about gnu-parallel but after installing as per the command i get a different error

Processing class 03001627
Converting meshes to OFF
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

Scaling meshes
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zash/anaconda3/envs/mesh_funcspace/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/zash/anaconda3/envs/mesh_funcspace/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "../external/mesh-fusion/1_scale.py", line 114, in run_file
    mesh = common.Mesh.from_off(filepath)
  File "/home/zash/Desktop/occupancy_networks-master/external/mesh-fusion/common.py", line 471, in from_off
    vertices, faces = read_off(filepath)
  File "/home/zash/Desktop/occupancy_networks-master/external/mesh-fusion/common.py", line 140, in read_off
    assert num_vertices > 0
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../external/mesh-fusion/1_scale.py", line 165, in <module>
    app.run()
  File "../external/mesh-fusion/1_scale.py", line 111, in run
    p.map(self.run_file, files)
  File "/home/zash/anaconda3/envs/mesh_funcspace/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zash/anaconda3/envs/mesh_funcspace/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
AssertionError
Create depths maps
Traceback (most recent call last):
  File "../external/mesh-fusion/2_fusion.py", line 11, in <module>
    import librender
  File "/home/zash/Desktop/occupancy_networks-master/external/mesh-fusion/librender/__init__.py", line 6, in <module>
    from librender.pyrender import *
ModuleNotFoundError: No module named 'librender.pyrender'
Produce watertight meshes
Traceback (most recent call last):
  File "../external/mesh-fusion/2_fusion.py", line 11, in <module>
    import librender
  File "/home/zash/Desktop/occupancy_networks-master/external/mesh-fusion/librender/__init__.py", line 6, in <module>
    from librender.pyrender import *
ModuleNotFoundError: No module named 'librender.pyrender'

**Comment by itszash** [comment]
yes @LMescheder i built the meshfusion and run the usage example to test it works fine but i think i didn't added the pyrender in $PYTHONPATH and thats the issue here... i tried different commad but it isn;t working can you tell me how can i add pyrender in $PYTHONPATH?

**Comment by itszash** [comment]
@LMescheder it will be great if you reply
when it import pyrender but when i run librender.pyrender i get this error can you tell me whats wrong...i tried building meshfusion multiple time but getting the same issue

**Comment by ankushpanwar19** [comment]
Did you find the answer to the issue?
I am getting the same issue with  'librender.pyrender'

**Comment by MaybeOjbk** [comment]
> @LMescheder it will be great if you reply
> when it import pyrender but when i run librender.pyrender i get this error can you tell me whats wrong...i tried building meshfusion multiple time but getting the same issue
how do you solve the problem ? I am really want to the how to fix it

**Comment by zhaoyuanyuan2011** [comment]
I got the same error. Has anyone found a solution?

**Comment by MaybeOjbk** [comment]
I guass I fixed the error,you should follow  the construction " python setup.py build_ext --inplace" ,try to build to say if there is something wrong left

**Comment by twcostain** [comment]
In the spirit of [973](https://xkcd.com/979/). You need to manually build all of the modules in `external/mesh-fusion`. You also need to manually build the gup code in libfusiongpu.
