### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by ChauncyFr** [autonomousvision/occupancy_networks#5]
When I execute the following command, an error occurs:
`python generate.py configs/demo.yaml`

Error：

```
https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_img2mesh_3-f786b04a.pt
=> Loading checkpoint from url...
Downloading: "https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_img2mesh_3-f786b04a.pt" to /home/fxru/.torch/models/onet_img2mesh_3-f786b04a.pt
Traceback (most recent call last):
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 46, in <module>
    checkpoint_io.load(cfg['test']['model_file'])
  File "/home/fxru/tensorflow_learn/occupancy_networks-master/im2mesh/checkpoints.py", line 47, in load
    return self.load_url(filename)
  File "/home/fxru/tensorflow_learn/occupancy_networks-master/im2mesh/checkpoints.py", line 78, in load_url
    state_dict = model_zoo.load_url(url, progress=True)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 76, in _download_url_to_file
    u = urlopen(url)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/fxru/anaconda3/envs/mesh_funcspace/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

```

**Comment by craigstar** [comment]
I have the same problem. Any help?
