### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'probs'

### ISSUE THREAD

**Issue by qiao1025566574** [autonomousvision/occupancy_networks#54]
Hello, @LMescheder @m-niemeyer !
When I run the train.py code, it always reports this error.

``` Total number of parameters: 13414465
[Epoch 01] it=010, loss=378.7144
[Epoch 01] it=020, loss=332.2954
Visualizing
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    trainer.visualize(data_vis)
  File "/home/qiaoguanhui/pycharm/occupancy_networks/im2mesh/onet/training.py", line 136, in visualize
    occ_hat = p_r.probs.view(batch_size, *shape)
AttributeError: 'Tensor' object has no attribute 'probs' 
```
I can't find where the 'probs' is. I am sure my anaconda environment is correctly since I can run demo and get normal result.

**Comment by qiao1025566574** [comment]
Sorry, that's my mistake. I used to change the code 'return p_r' to 'return c'. Tensor 'c' has no attribute 'probs', and tensor p_r has 'probs'.
