### ISSUE TITLE
two problem

### ISSUE THREAD

**Issue by zyz-1998** [autonomousvision/occupancy_networks#68]
in the Anaconda
(mesh_funcspace) E:\occupancy_networks-master>python setup.py build_ext --inplace
running build_ext
D:\SoftWare\Anaconda\envs\mesh_funcspace\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'im2mesh.utils.libkdtree.pykdtree.kdtree' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

(mesh_funcspace) E:\occupancy_networks-master>python generate.py configs/demo.yaml
Traceback (most recent call last):
  File "generate.py", line 10, in <module>
    from im2mesh import config
  File "E:\occupancy_networks-master\im2mesh\config.py", line 4, in <module>
    from im2mesh import onet, r2n2, psgn, pix2mesh, dmc
  File "E:\occupancy_networks-master\im2mesh\onet\__init__.py", line 1, in <module>
    from im2mesh.onet import (
  File "E:\occupancy_networks-master\im2mesh\onet\config.py", line 5, in <module>
    from im2mesh.encoder import encoder_dict
  File "E:\occupancy_networks-master\im2mesh\encoder\__init__.py", line 1, in <module>
    from im2mesh.encoder import (
  File "E:\occupancy_networks-master\im2mesh\encoder\conv.py", line 4, in <module>
    from im2mesh.common import normalize_imagenet
  File "E:\occupancy_networks-master\im2mesh\common.py", line 3, in <module>
    from im2mesh.utils.libkdtree import KDTree
  File "E:\occupancy_networks-master\im2mesh\utils\libkdtree\__init__.py", line 1, in <module>
    from .pykdtree.kdtree import KDTree
ModuleNotFoundError: No module named 'im2mesh.utils.libkdtree.pykdtree.kdtree'

**Comment by aryanna384** [comment]
same as you，did you solve it？

**Comment by JHGeng** [comment]
I have the same question as your second question of “No module named 'im2mesh.utils.libkdtree.pykdtree.kdtree' ”,did you have
solved it? help me please
