### ISSUE TITLE
No module named 'im2mesh.utils.libkdtree.pykdtree.kdtree'

### ISSUE THREAD

**Issue by MASTERCHIEF343** [autonomousvision/occupancy_networks#7]
Hi, I have some problems with code's configuration.I google it but not found a proper solution.I also follow 'conda env create -f environment.yaml ', but there's something wrong with my network that i can't download.Do you know how to fix this?

**Comment by LMescheder** [comment]
Hi @MASTERCHIEF343 ,
could you please provide more details to reproduce your problem? What did you try to achieve? What is the error message? ...

**Comment by MASTERCHIEF343** [comment]
(mesh_funcspace) D:\TF_GPU\occupancy_networks-master>python generate.py configs/demo.yaml
Traceback (most recent call last):
  File "generate.py", line 10, in <module>
    from im2mesh import config
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\config.py", line 4, in <module>
    from im2mesh import onet, r2n2, psgn, pix2mesh, dmc
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\onet\__init__.py", line 1, in <module>
    from im2mesh.onet import (
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\onet\config.py", line 5, in <module>
    from im2mesh.encoder import encoder_dict
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\encoder\__init__.py", line 1, in <module>
    from im2mesh.encoder import (
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\encoder\conv.py", line 4, in <module>
    from im2mesh.common import normalize_imagenet
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\common.py", line 3, in <module>
    from im2mesh.utils.libkdtree import KDTree
  File "D:\TF_GPU\occupancy_networks-master\im2mesh\utils\libkdtree\__init__.py", line 1, in <module>
    from .pykdtree.kdtree import KDTree
ModuleNotFoundError: No module named 'im2mesh.utils.libkdtree.pykdtree.kdtree'

Sorry, i didn't make myself clear.This is my error,i don't know how to fix it.

**Comment by munachisonwadike** [comment]
Did anyone find the answer to this?

**Comment by LMescheder** [comment]
pykdtree should be automatically built when running

```
python setup.py build_ext --inplace
```

Can you verify that the build step was successful?

**Comment by JeremyFisher** [comment]
I am having a similar problem. After doing

python setup.py build_ext --inplace

i am seeing:
running build_ext
building 'im2mesh.utils.libkdtree.pykdtree.kdtree' extension
gcc -pthread -B /home/mat/anaconda3/envs/mesh_funcspace/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mat/anaconda3/envs/mesh_funcspace/include/python3.6m -c im2mesh/utils/libkdtree/pykdtree/kdtree.c -o build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o -std=c99 -O3 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=kdtree -D_GLIBCXX_USE_CXX11_ABI=0
im2mesh/utils/libkdtree/pykdtree/kdtree.c:525:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Here is how i fixed this:**
first you check in python where is your numpy:
import numpy
numpy.get_include()

and then before installing you do:
export CFLAGS=-I/<path_to_include>

in my case it was:
export ### CFLAGS=-I/home/jeremy/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/numpy/core/include/

**Comment by Chulabhaya** [comment]
Thanks to @JeremyFisher's fix, I get past the same error that he's having, but then I'm immediately met with another error:

gcc -pthread -B /home/chulabhaya/anaconda3/envs/mesh_funcspace/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/chulabhaya/anaconda3/lib/python3.7/site-packages/numpy/core/include -fPIC -I/home/chulabhaya/anaconda3/envs/mesh_funcspace/include/python3.6m -c im2mesh/utils/libkdtree/pykdtree/_kdtree_core.c -o build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/_kdtree_core.o -std=c99 -O3 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=kdtree -D_GLIBCXX_USE_CXX11_ABI=0
gcc -pthread -shared -B /home/chulabhaya/anaconda3/envs/mesh_funcspace/compiler_compat -L/home/chulabhaya/anaconda3/envs/mesh_funcspace/lib -Wl,-rpath=/home/chulabhaya/anaconda3/envs/mesh_funcspace/lib -Wl,--no-as-needed -Wl,--sysroot=/ -I/home/chulabhaya/anaconda3/lib/python3.7/site-packages/numpy/core/include build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/_kdtree_core.o -o build/lib.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.cpython-36m-x86_64-linux-gnu.so -lgomp
/home/chulabhaya/anaconda3/envs/mesh_funcspace/compiler_compat/ld: build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o: unable to initialize decompress status for section .debug_info
/home/chulabhaya/anaconda3/envs/mesh_funcspace/compiler_compat/ld: build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o: unable to initialize decompress status for section .debug_info
/home/chulabhaya/anaconda3/envs/mesh_funcspace/compiler_compat/ld: build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o: unable to initialize decompress status for section .debug_info
/home/chulabhaya/anaconda3/envs/mesh_funcspace/compiler_compat/ld: build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o: unable to initialize decompress status for section .debug_info
**build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o: file not recognized: file format not recognized**
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

Any ideas as to what might be causing this, and how to fix it? Thanks in advance!

**Comment by spha-code** [comment]
I managed to solve a similar problem simply by running:

conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

**Comment by spha-code** [comment]
> I am having a similar problem. After doing
> 
> python setup.py build_ext --inplace
> 
> i am seeing:
> running build_ext
> building 'im2mesh.utils.libkdtree.pykdtree.kdtree' extension
> gcc -pthread -B /home/mat/anaconda3/envs/mesh_funcspace/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mat/anaconda3/envs/mesh_funcspace/include/python3.6m -c im2mesh/utils/libkdtree/pykdtree/kdtree.c -o build/temp.linux-x86_64-3.6/im2mesh/utils/libkdtree/pykdtree/kdtree.o -std=c99 -O3 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=kdtree -D_GLIBCXX_USE_CXX11_ABI=0
> im2mesh/utils/libkdtree/pykdtree/kdtree.c:525:10: fatal error: numpy/arrayobject.h: No such file or directory
> #include "numpy/arrayobject.h"
> ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> 
> **Here is how i fixed this:**
> first you check in python where is your numpy:
> import numpy
> numpy.get_include()
> 
> and then before installing you do:
> export CFLAGS=-I/<path_to_include>
> 
> in my case it was:
> export CFLAGS=-I/home/jeremy/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/numpy/core/include/

I have the exact same problem now but when I run this command in python I get an error. See below. Any hints? thanks!

    export CFLAGS=-I/home/user/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/numpy/core/include
                ^
SyntaxError: invalid syntax

**Comment by Edwinzero** [comment]
I found a solution when I build this on windows platform. You can simply add `include_dirs=[numpy_include_dir]` to each module definition in the setup.py instead of calling anything from the command-line tool.
