### ISSUE TITLE
ERROR WHILE TRAINING.

### ISSUE THREAD

**Issue by ALI7861111** [autonomousvision/occupancy_networks#70]
While training my custom data following error occurs. while executing this line ..
My preprocessing is perfect .
This is the command  I ran.
................................................................................................
!python train.py configs/img/onet.yaml
......................................................................................................
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    train_dataset = config.get_dataset('train', cfg)
  File "/content/occupancy_networks/im2mesh/config.py", line 152, in get_dataset
    categories=categories,
  File "/content/occupancy_networks/im2mesh/data/core.py", line 86, in __init__
    with open(split_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ShapeNet/03001627/train.lst'

**Comment by ALI7861111** [comment]
!python /content/occupancy_networks/scripts/create_split.py /content/occupancy_networks/data/ShapeNet/03001627 --r_val 0.1 --r_test 0.2

files created by following command .. make your required paths as relative to your system
