### ISSUE TITLE
demo on the CPU 

### ISSUE THREAD

**Issue by riccardosemprevivo** [autonomousvision/occupancy_networks#91]
I get this error when i try to run the demo on the cpu:

 python generate.py configs/demo.yaml
https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_img2mesh_3-f786b04a.pt
=> Loading checkpoint from url...
Traceback (most recent call last):
  File "generate.py", line 46, in <module>
    checkpoint_io.load(cfg['test']['model_file'])
  File "/home/ubuntu/Documents/occupancy_networks-master/im2mesh/checkpoints.py", line 47, in load
    return self.load_url(filename)
  File "/home/ubuntu/Documents/occupancy_networks-master/im2mesh/checkpoints.py", line 78, in load_url
    state_dict = model_zoo.load_url(url, progress=True)
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 67, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/serialization.py", line 504, in persistent_load
    data_type(size), location)
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/serialization.py", line 113, in default_restore_location
    result = fn(storage, location)
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/serialization.py", line 94, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/ubuntu/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/serialization.py", line 78, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

**Comment by mitesuti** [comment]
Hello.

I, too, would like to run this program on my CPU.
However, I am getting many errors at compile time. (like m.lib not found...)
Were you able to finally run it on cpu? Also, I would like to know if there are any changes or innovations you made at that time.

Best regards
