### ISSUE TITLE
training with default.yaml

### ISSUE THREAD

**Issue by NaveedMaz** [autonomousvision/occupancy_networks#94]
hi,
want to train this network to my custom data i have prepared everything and all the data just as stated in the repo but when i train it it gives me this error
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    model = config.get_model(cfg, device=device, dataset=train_dataset)
  File "/home/mazharnaveed804/experimental/occupancy_networks/im2mesh/config.py", line 76, in get_model
    cfg, device=device, dataset=dataset)
  File "/home/mazharnaveed804/experimental/occupancy_networks/im2mesh/onet/config.py", line 35, in get_model
    encoder_latent = models.encoder_latent_dict[encoder_latent](
KeyError: None
Now i don't know how can i solve it please help.

**Comment by NaveedMaz** [comment]
it is giving me the same error when i try to train on the preprocessed shapenet data provided in this repo

**Comment by tsunghan-mama** [comment]
Me too.

**Comment by tsunghan-mama** [comment]
I met the same problem too.
After a lot of trial-and-error, I found that the following scripts are able to run successfully.

```bash
python3 train.py configs/img/onet.yaml
python3 train.py configs/pointcloud/onet.yaml
python3 train.py configs/voxels/onet.yaml
```

Just would like to share my findings and hope it will help you.

**Comment by Hxinyue** [comment]
> I met the same problem too. After a lot of trial-and-error, I found that the following scripts are able to run successfully.
> 
> ```shell
> python3 train.py configs/img/onet.yaml
> python3 train.py configs/pointcloud/onet.yaml
> python3 train.py configs/voxels/onet.yaml
> ```
> 
> Just would like to share my findings and hope it will help you.

Hello, there are a lot of yaml files in the whole configuration file in the file, do they all mean anything different?
We look forward to your reply thanks.
